server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: movies-service
          uri: lb://PTV-MOVIES
          predicates:
            - Path=/ms-movies/**
          filters:
            - StripPrefix=1